POST http://localhost:8080/user
Content-Type: application/json

{
"id": 23,
"name": "Test 112",
"username": "test41 ",
"password": "test 2"
}

###

GET  http://localhost:8080/user

###
POST http://localhost:8080/user/calc
Content-Type: application/json

{
"id": 12,
"num1": 114,
"num2": 12,
"type": "SUM"
}

###